# Generated by Django 5.2.6 on 2025-10-01 13:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricula', models.CharField(max_length=14)),
                ('senha', models.CharField(max_length=128)),
                ('ativo', models.BooleanField(default=True)),
                ('ultimo_login', models.DateField(auto_now=True)),
                ('criado_em', models.DateField(auto_now_add=True)),
                ('atualizado_em', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Instituicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('endereco', models.CharField(max_length=255)),
                ('cnpj', models.CharField(max_length=18)),
                ('exige_vinculo', models.BooleanField(default=False)),
                ('email', models.CharField(max_length=254)),
                ('telefone', models.CharField(max_length=20)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instituicoes', to='backend.usuario')),
            ],
        ),
    ]
